main_assem:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Veloctity Control

  back_l_controller:
    type: effort_controllers/JointVelocityController
    joint: back_l_j
    pid: {p: 4000.0, i: 50.0, d: 100.0}

  back_r_controller:
    type: effort_controllers/JointVelocityController
    joint: back_r_j
    pid: {p: 4000.0, i: 50.0, d: 100.0}

  # Position Control

  armbase_controller:
    type: effort_controllers/JointPositionController
    joint: armbase_j
    pid: {p: 2000.0, i: 50.0, d: 100.0}

  arm1_controller:
    type: effort_controllers/JointPositionController
    joint: arm1_j
    pid: {p: 2000.0, i: 50.0, d: 100.0}
  
  arm2_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_j
    pid: {p: 2000.0, i: 50.0, d: 100.0}
  
  arm3_controller:
    type: effort_controllers/JointPositionController
    joint: arm3_j
    pid: {p: 2000.0, i: 50.0, d: 100.0}

  end_eff_controller:
    type: effort_controllers/JointPositionController
    joint: end_eff_j
    pid: {p: 2000.0, i: 50.0, d: 100.0}